version: '3.7'

services: 
  # PHP-Fpm Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm-alpine
    container_name: niagahoster-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/niagahoster
    networks: 
      - niagahoster-network

  # nginx
  webserver:
    image: nginx:alpine
    container_name: niagahoster-webserver
    restart: unless-stopped
    tty: true
    ports: 
      - "81:80"
      - "444:443"
    volumes: 
      - ./:/var/www/html/niagahoster
      - ./docker-files/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    networks: 
      - niagahoster-network
  
  # db
  db:
    image: mysql:5.7.22
    container_name: niagahoster-db
    restart: unless-stopped
    tty: true
    ports: 
      - "3307:3306"
    environment: 
      MYSQL_DATABASE: niagahoster_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - niagahoster-network

networks:
  niagahoster-network:
    driver: bridge
