version: '3'

services: 
  # PHP-Fpm Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: niagahoster-test-web
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks: 
      - app-network

  # nginx
  webserver:
    image: nginx:alpine
    container_name: niagahoster-webserver
    restart: unless-stopped
    tty: true
    ports: 
      - "8100:80"
      - "8143:443"

    volumes: 
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

    networks: 
      - app-network
  
  # db
  db:
    image: mariadb:10.5.6
    container_name: db
    restart: unless-stopped
    tty: true
    ports: 
      - "3307:3306"

    environment: 
      MYSQL_DATABASE: niagahoster_db
      MYSQL_ROOT_PASSWORD: root

    volumes: 
      - mariadbdata:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    
    networks: 
      - app-network

volumes:
  mariadbdata:
    driver: local


networks:
  app-network:
    driver: bridge
